CREATE VIEW SUPPLIER_PART_SUMMARY AS
SELECT 
    S.SUPPLIER_ID,
    S.SUPPLIER_NAME,
    P.PART_ID,
    COUNT(*) AS SUPPLY_COUNT,
    MAX(D.DELIVERY_DATE) AS LAST_DELIVERY
FROM SUPPLIERS S
JOIN DELIVERY_DETAILS D ON S.SUPPLIER_ID = D.SUPPLIER_ID
JOIN PART_MASTER P ON D.PART_ID = P.PART_ID
GROUP BY S.SUPPLIER_ID, S.SUPPLIER_NAME, P.PART_ID;
