INSERT INTO MATERIAL_USAGE_LOG (WORK_ORDER_ID, PART_ID, USED_QTY, USAGE_TIMESTAMP)
SELECT 
    W.WORK_ORDER_ID,
    BOM.COMPONENT_PART_ID,
    BOM.QTY * W.PRODUCTION_QUANTITY AS USED_QTY,
    CURRENT_TIMESTAMP
FROM WORK_ORDERS W
JOIN PRODUCT_BOM BOM ON W.PRODUCT_ID = BOM.PRODUCT_ID
JOIN INVENTORY_MASTER IM ON IM.PART_ID = BOM.COMPONENT_PART_ID
WHERE W.STATUS = 'RELEASED'
  AND IM.QUANTITY >= (BOM.QTY * W.PRODUCTION_QUANTITY)
  AND NOT EXISTS (
      SELECT 1 FROM MATERIAL_USAGE_LOG M
      WHERE M.WORK_ORDER_ID = W.WORK_ORDER_ID AND M.PART_ID = BOM.COMPONENT_PART_ID
  );
