INSERT INTO REORDER_QUEUE (PART_ID, WAREHOUSE_ID, REQUIRED_QTY, SUGGESTED_DATE)
SELECT 
    I.PART_ID,
    I.LOCATION_ID,
    (R.REORDER_LEVEL - I.QUANTITY) AS REQUIRED_QTY,
    CURRENT_DATE
FROM INVENTORY_MASTER I
JOIN REORDER_RULES R ON I.PART_ID = R.PART_ID
WHERE I.QUANTITY < R.REORDER_LEVEL
  AND NOT EXISTS (
      SELECT 1 FROM REORDER_QUEUE Q
      WHERE Q.PART_ID = I.PART_ID AND Q.WAREHOUSE_ID = I.LOCATION_ID
  );
