UPDATE INVENTORY_MASTER
SET QUANTITY = QUANTITY + (
    SELECT SUM(DELIVERED_QTY)
    FROM DELIVERY_DETAILS
    WHERE PART_ID = 'P12345' AND DELIVERY_DATE = CURRENT_DATE
)
WHERE PART_ID = 'P12345' AND LOCATION_ID = 'WH01';
